apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
  namespace: devops-k8s-dotnet-project
spec:
  type: ClusterIP
  ports:
    - port: 1433
      targetPort: 1433
      protocol: TCP
  selector:
    app: sqlserver