apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
  namespace: devops-k8s-dotnet-project
type: Opaque
data:
  sa-password: QWRtaW5AMTIz  # base64 encoded password
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: devops-k8s-dotnet-project
type: Opaque
data:
  connection-string: U2VydmVyPXNxbHNlcnZlci1zZXJ2aWNlO2RhdGFiYXNlPUVtcGxveWVlRGI7VXNlciBJZD1zYTtQYXNzd29yZD1BZG1pbkAxMjM7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT10cnVlOw==  # base64 encoded connection string