apiVersion: v1
kind: Service
metadata:
  name: employee-api-service
  namespace: devops-k8s-dotnet-project
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  
  selector:
    app: employeeapp-webapi